PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS config (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  price_with_pass_cents INTEGER NOT NULL DEFAULT 1500,
  price_without_pass_cents INTEGER NOT NULL DEFAULT 3000,
  max_car_capacity INTEGER NOT NULL DEFAULT 5
);

INSERT OR IGNORE INTO config (id) VALUES (1);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  has_pass INTEGER NOT NULL DEFAULT 0,
  is_driver INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (DATETIME('now'))
);

CREATE TABLE IF NOT EXISTS cars (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  driver_id INTEGER NOT NULL UNIQUE,
  capacity INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (DATETIME('now')),
  FOREIGN KEY (driver_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS car_passengers (
  car_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL UNIQUE,
  PRIMARY KEY (car_id, user_id),
  FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);